qt4-native: depend on icu-native to fix build on systems with icu <=58
Previously, qt4-native would use the system icu to build.

Trying to build against a system ICU 59, however, fails with this root
error:

| In file included from /usr/include/unicode/uversion.h:30:0,
|                  from tools/qlocale_icu.cpp:46:
| /usr/include/unicode/umachine.h:347:13: error: ‘char16_t’ does not name a type; did you mean ‘wchar_t’?
|      typedef char16_t UChar;
|              ^~~~~~~~
|              wchar_t

May have to do with our use of `-std=gnu98++`.

Signed-off-by: Cody P Schafer <dev@codyps.com>
Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>